---
name: 'Secret'
description: 'Get secrets from vault'
inputs:
  vaultPath: 
    description: 'path to secret'
    required: true
outputs:
  creds: 
    description: 'credentials from vault'
runs:
  using: 'node12'
  main: 'index.js'
