---
name: 'Secret'
description: 'Get secrets from vault'
inputs:
  ROLE_ID: 
    description: 'Role ID for vault login'
    required: true
  SECRET_ID: 
    description: 'Secret ID for vault login'
    required: true
  vaultPath: 
    description: 'path to secret'
    required: true
outputs:
  creds: 
    description: 'credentials from vault'
runs:
  using: 'node12'
  main: 'index.js'
