---
name: 'Secret'
description: 'Get secrets from vault'
inputs:
  role-id: 
    description: 'Role ID for vault login'
    required: true
  secret-id: 
    description: 'Secret ID for vault login'
    required: true
  secret-paths: 
    description: 'path to secret'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
