---
'on':
  push:
    branches:
      - master
jobs:
  get_secrets:
    runs-on: self-hosted
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get secrets
        uses: ./
        id: secret
        with:
          role-id: 774e2757-4579-c411-4d04-68477ccf19ff
          secret-id: ${{ secrets.APPROLE_SECRET_ID }}
          secret-paths: |
            {
              "usr" : ["secret/hello-world/user-pass", "username"],
              "pass" : ["secret/hello-world/user-pass", "password"],
              "id" : ["secret/hello-world/id"]
            }

      - name: Echoing Results
        run: |
          echo ${{ steps.secret.outputs }}
      - name: Automated Testing
        run: |
          test "USERNAME_VAL" = "${{ steps.secret.outputs.usr }}"
          test "PASSWORD_VAL" = "${{ steps.secret.outputs.pass }}"
          test "99999" = "${{ fromJson(steps.secret.outputs.id).ID_Number }}"
          test "rudra_desai@colpal.com" \
               = "${{ fromJson(steps.secret.outputs.id).email }}"

      - uses: colpal/actions-clean@v1
        if: ${{ always() }}
