on: [push]

jobs:
  get_secrets:
    runs-on: self-hosted
    name: An action to get secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get secrets
        uses: ./
        id: secret
        with:
          vaultPath: '/secret/teams/intern-training'

      - name: Get the output creds
        run: echo "Creds returned - ${{ steps.secret.outputs.creds }}"

      - name: Checking vault connection
        run: vault status