---
name: 'Test'
on: push

jobs:
  get_secrets:
    runs-on: ubuntu-latest
    name: An action to get secrets
    steps:
    - name: Get secrets
      id: secret
      uses: actions/checkout@v2
      with:
        vaultPath: '/secret/teams/intern-training'

    - name: Get the output time
      run: echo "Creds returned - ${{ steps.secret.outputs.creds }}"