on: 
  push:
    branches:
      - async/await
jobs:
  get_secrets:
    runs-on: self-hosted
    name: An action to get secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get secrets
        uses: ./
        id: secret
        with:
          ROLE_ID: 774e2757-4579-c411-4d04-68477ccf19ff
          SECRET_ID: ${{ secrets.APPROLE_SECRET_ID }}
          vaultPath: |
            {
              "usr" : ["secret/hello-world/user-pass", "username"],
              "pass" : ["secret/hello-world/user-pass", "password"],
              "id" : ["secret/hello-world/id"]
            }
      - run: test "WRONG_USERNAME" = "${{ fromJson(steps.secret.outputs.creds).usr }}" && echo "True" || echo "False"

        
      - uses: colpal/actions-clean@v1.0.2
        if: ${{ always() }}
        
