on: 
  push:
    branches:
      - master
jobs:
  get_secrets:
    runs-on: self-hosted
    name: An action to get secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get secrets
        uses: ./
        id: secret
        with:
          ROLE_ID: 774e2757-4579-c411-4d04-68477ccf19ff
          SECRET_ID: ${{ secrets.APPROLE_SECRET_ID }}
          secret-paths: |
            {
              "usr" : ["secret/hello-world/user-pass", "username"],
              "pass" : ["secret/hello-world/user-pass", "password"],
              "id" : ["secret/hello-world/dontExist"]
            }
      - name: Automated Testing
        run: | 
          test "USERNAME_VAL" = "${{ steps.secret.outputs.usr }}"
          test "PASSWORD_VAL" = "${{ steps.secret.outputs.pass }}"
          test "99999" = "${{ fromJson(steps.secret.outputs.id).ID_Number }}"
          test "rudra_desai@colpal.com" = "${{ fromJson(steps.secret.outputs.id).email }}"

      - uses: colpal/actions-clean@v1.0.2
        if: ${{ always() }}
        
