on: [push]

jobs:
  get_secrets:
    runs-on: self-hosted
    name: An action to get secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get secrets
        uses: ./
        id: secret
        with:
          ROLE_ID: 774e2757-4579-c411-4d04-68477ccf19ff
          SECRET_ID: ${{ secrets.APPROLE_SECRET_ID }}
          vaultPath: '/secret/hello-world'

      - name: Get the output creds
        run: echo "Creds returned - ${{ steps.secret.outputs.creds }}"
        
      - uses: colpal/actions-clean@v1.0.2
        if: ${{ always() }}
        
