on: 
  push:
    branches:
      - async/await
jobs:
  get_secrets:
    runs-on: self-hosted
    name: An action to get secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get secrets
        uses: ./
        id: secret
        with:
          ROLE_ID: 774e2757-4579-c411-4d04-68477ccf19ff
          SECRET_ID: ${{ secrets.APPROLE_SECRET_ID }}
          vaultPath: |
            {
              "usr" : ["secret/hello-world/user-pass", "username"],
              "pass" : ["secret/hello-world/user-pass", "password"],
              "id" : ["secret/hello-world/id"]
            }
      - name: Automated Testing
        run: | 
          test "USERNAME_VAL" = "${{ fromJson(steps.secret.outputs.creds).usr }}" || exit 1;
          test "PASSWORD_VAL" = "${{ fromJson(steps.secret.outputs.creds).pass }}" || exit 1;
          test "99999" = "${{ fromJson(steps.secret.outputs.creds).id.ID_Number }}" || exit 1;
          test "rudra_desai@colpal.com" = "${{ fromJson(steps.secret.outputs.creds).id.email }}" || exit 1;

      - uses: colpal/actions-clean@v1.0.2
        if: ${{ always() }}
        
